#!/bin/bash
# NIXL Host Installation - Build NIXL and NIXLBench
# This script can be run without sudo

set -e

# Configuration — all output goes under $NIXL_SOURCE_DIR/install/
NIXL_SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NIXL_INSTALL_PREFIX="${NIXL_INSTALL_PREFIX:-$NIXL_SOURCE_DIR/install/nixl}"
NIXLBENCH_INSTALL_PREFIX="${NIXLBENCH_INSTALL_PREFIX:-$NIXL_SOURCE_DIR/install/nixlbench}"
NIXLBENCH_SOURCE_DIR="${NIXL_SOURCE_DIR}/benchmark/nixlbench"
BUILD_TYPE="${BUILD_TYPE:-release}"

echo "=== NIXL Host Installation - Build ==="
echo ""
echo "Configuration:"
echo "  Source Directory: $NIXL_SOURCE_DIR"
echo "  NIXL Install Prefix: $NIXL_INSTALL_PREFIX"
echo "  NIXLBench Install Prefix: $NIXLBENCH_INSTALL_PREFIX"
echo "  Build Type: $BUILD_TYPE"
echo ""

# Clean previous install artifacts (headers, libraries, binaries)
echo "[0/5] Cleaning previous build artifacts..."
rm -rf \
  "$NIXL_INSTALL_PREFIX/include" \
  "$NIXL_INSTALL_PREFIX/lib" \
  "$NIXL_INSTALL_PREFIX/bin" \
  "$NIXLBENCH_INSTALL_PREFIX/include" \
  "$NIXLBENCH_INSTALL_PREFIX/lib" \
  "$NIXLBENCH_INSTALL_PREFIX/bin"
echo "    ✓ Cleaned"
echo ""

# Create virtual environment if needed
if [ ! -d ".venv" ]; then
  echo "[1/5] Creating Python virtual environment..."
  python3.12 -m venv .venv
  source .venv/bin/activate
  pip install --upgrade pip setuptools wheel
  pip install meson pybind11 patchelf pyYAML click tabulate torch
else
  echo "[1/5] Using existing Python virtual environment..."
  source .venv/bin/activate
fi

# Build NIXL
echo "[2/5] Building NIXL library..."
cd "$NIXL_SOURCE_DIR"
rm -rf build
meson setup build --prefix=$NIXL_INSTALL_PREFIX --buildtype=$BUILD_TYPE
cd build
ninja
echo "    ℹ Next: sudo ninja install (requires root)"

echo "[3/5] Installing NIXL..."
ninja install
echo "    ✓ NIXL installed to: $NIXL_INSTALL_PREFIX"

# Install NIXL Python package into venv (requires the build dir to exist)
echo "    Installing NIXL Python package..."
cd "$NIXL_SOURCE_DIR"
pip install --no-build-isolation -e . --quiet
echo "    ✓ NIXL Python package installed"

# Build NIXLBench
echo ""
echo "[4/5] Building NIXLBench benchmark tool..."
cd "$NIXLBENCH_SOURCE_DIR"
rm -rf build
meson setup build \
  -Dnixl_path=$NIXL_INSTALL_PREFIX/ \
  -Dprefix=$NIXLBENCH_INSTALL_PREFIX \
  --buildtype=$BUILD_TYPE
cd build
ninja
echo "[5/5] Installing NIXLBench..."
ninja install
echo "    ✓ NIXLBench installed to: $NIXLBENCH_INSTALL_PREFIX"

echo ""
echo "=== Build & Installation Complete ==="
echo ""
echo "✓ NIXL:       $NIXL_INSTALL_PREFIX"
echo "✓ NIXLBench:  $NIXLBENCH_INSTALL_PREFIX"

# Generate env.sh for environment variable setup
ARCH=$(uname -m)
[ "$ARCH" = "arm64" ] && ARCH="aarch64"
ENV_FILE="$NIXL_SOURCE_DIR/env.sh"

cat > "$ENV_FILE" << EOF
# Auto-generated by build.sh — source this file to use NIXL and NIXLBench
# Usage: source $(basename $ENV_FILE)
# Tear down: rm -rf $NIXL_SOURCE_DIR

export NIXL_SOURCE_DIR="$NIXL_SOURCE_DIR"
export NIXL_INSTALL_PREFIX="$NIXL_INSTALL_PREFIX"
export NIXLBENCH_INSTALL_PREFIX="$NIXLBENCH_INSTALL_PREFIX"

export PATH="$NIXLBENCH_INSTALL_PREFIX/bin:$NIXL_INSTALL_PREFIX/bin:\$PATH"
export LD_LIBRARY_PATH="$NIXLBENCH_INSTALL_PREFIX/lib:$NIXL_INSTALL_PREFIX/lib:$NIXL_INSTALL_PREFIX/lib/$ARCH-linux-gnu:$NIXL_INSTALL_PREFIX/lib/$ARCH-linux-gnu/plugins:\$LD_LIBRARY_PATH"
export NIXL_PLUGIN_DIR="$NIXL_INSTALL_PREFIX/lib/$ARCH-linux-gnu/plugins"

# Activate Python virtual environment
if [ -f "$NIXL_SOURCE_DIR/.venv/bin/activate" ]; then
    source "$NIXL_SOURCE_DIR/.venv/bin/activate"
fi
EOF

echo ""
echo "✅ env.sh 생성됨: $ENV_FILE"
echo ""
echo "📌 사용법:"
echo "  source ./env.sh          # 환경 변수 설정"
echo "  ./run_nixlbench.sh POSIX # 벤치마크 실행"
echo ""
echo "🗑  Tear down:"
echo "  rm -rf $NIXL_SOURCE_DIR  # 전체 삭제 (빌드 결과 포함)"
echo ""
echo "✅ sudo 필요 없음! 모든 설치가 완료되었습니다."
echo ""
