# Auto-generated by build.sh — source this file to use NIXL and NIXLBench
# Usage: source env.sh
# Tear down: rm -rf /home/gj/nixl

export NIXL_SOURCE_DIR="/home/gj/nixl"
export NIXL_INSTALL_PREFIX="/home/gj/nixl/install/nixl"
export NIXLBENCH_INSTALL_PREFIX="/home/gj/nixl/install/nixlbench"

export PATH="/home/gj/nixl/install/nixlbench/bin:/home/gj/nixl/install/nixl/bin:$PATH"
export LD_LIBRARY_PATH="/home/gj/nixl/install/nixlbench/lib:/home/gj/nixl/install/nixl/lib:/home/gj/nixl/install/nixl/lib/x86_64-linux-gnu:/home/gj/nixl/install/nixl/lib/x86_64-linux-gnu/plugins:$LD_LIBRARY_PATH"
export NIXL_PLUGIN_DIR="/home/gj/nixl/install/nixl/lib/x86_64-linux-gnu/plugins"

# Activate Python virtual environment
if [ -f "/home/gj/nixl/.venv/bin/activate" ]; then
    source "/home/gj/nixl/.venv/bin/activate"
fi
