name: Publish Debian Package

on:
  push:
    branches: [main]

jobs:
  publish-noble:
    runs-on: self-hosted-noble
    env:
      APTLY_TOKEN: ${{ secrets.APTLY_TOKEN }}
      APTLY_URL: ${{ secrets.APTLY_URL }}
      APTLY_REPO: ${{ secrets.APTLY_REPO_NOBLE }}
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pbuilder devscripts debootstrap

      - name: Build
        run: sudo ./debian.sh build --tarball-dir ~/pbuilder

      - name: Remove existing packages from Aptly
        run: ./debian.sh aptly --remove nixl

      - name: Upload to Aptly
        run: ./debian.sh package --aptly

  publish-jammy:
    runs-on: self-hosted-medium
    env:
      APTLY_TOKEN: ${{ secrets.APTLY_TOKEN }}
      APTLY_URL: ${{ secrets.APTLY_URL }}
      APTLY_REPO: ${{ secrets.APTLY_REPO_JAMMY }}
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pbuilder devscripts debootstrap

      - name: Build
        run: sudo ./debian.sh build --jammy --tarball-dir ~/pbuilder

      - name: Remove existing packages from Aptly
        run: ./debian.sh aptly --remove nixl --jammy

      - name: Upload to Aptly
        run: ./debian.sh package --aptly --jammy
